default: &default
  adapter: postgresql
  encoding: unicode
  port: 5432  
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  url: postgres://rails:rails@127.0.0.1/veeqodemo_development

test:
  <<: *default
  url: postgres://rails:rails@127.0.0.1/veeqodemo_test

production:
  <<: *default
  url: <%= ENV["DATABASE_URL"] %>
