name: Deploy

on:
  workflow_call:
    inputs:
      ENVIRONMENT_NAME:
        required: true
        type: string
      REGION: 
        type: string
      VERSION: 
        type: string
    secrets:
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      DATABASE_NAME:
        required: true
      DATABASE_USER:
        required: true
      DATABASE_PASSWORD:
        required: true
      RAILS_APP_NAME:
        required: true
      RAILS_APP_SECRET_KEY_BASE:
        required: true

jobs:
  generate:
    name: 'Deploy'
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to EB
      uses: einaregilsson/beanstalk-deploy@v11
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: ${{ secrets.RAILS_APP_NAME }}
        environment_name: ${{ inputs.ENVIRONMENT_NAME }}
        version_label: ${{ inputs.VERSION }}
        region: ${{ inputs.REGION }}
        deployment_package: ${{ inputs.VERSION }}.zip
