name: CI + CD

on:
  push:
    branches: [ master ]

jobs:
  GenerateVersion:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.time.outputs.time }}
    steps:
    - name: Get Time
      id: time
      uses: nanzm/get-time-action@v1.1
      with:
        timeZone: 0
        format: 'YYYYMMDDHHmmss'
      
    - name: Generate deployment package
      run: |
        zip -r deploy.zip . -x '*.git*'
        
  Test:
    name: Run Tests
    needs: [GenerateVersion]
    uses: mikelazell/rails-fulfilment/.github/workflows/test.yml@master

  DeployTest:
    name: Deploy to Test 
    needs: [Test]
    uses: mikelazell/rails-fulfilment/.github/workflows/deploy.yml@master
    with:
      ENVIRONMENT_NAME: "test"
      REGION: "eu-west-2"
      VERSION: "1234"
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      RAILS_APP_NAME: ${{secrets.RAILS_APP_NAME}}
      RAILS_APP_SECRET_KEY_BASE: ${{secrets.RAILS_APP_SECRET_KEY_BASE}}

  DeployProd:
    name: Deploy to Prod 
    needs: [DeployTest]
    uses: mikelazell/rails-fulfilment/.github/workflows/deploy.yml@master
    with:
      ENVIRONMENT_NAME: "production"
      REGION: "eu-west-2"
      VERSION: "1234"
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      RAILS_APP_NAME: ${{secrets.RAILS_APP_NAME}}
      RAILS_APP_SECRET_KEY_BASE: ${{secrets.RAILS_APP_SECRET_KEY_BASE}}
