name: CI + CD

on:
  push:
    branches: [ master ]

jobs:
        
  Test:
    name: Run Tests
    uses: mikelazell/rails-fulfilment/.github/workflows/test.yml@master

  GenerateVersion:
    name: Generate Version
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Generate Version
      uses: paulhatch/semantic-version@v4.0.2
      id: version
      with:
        tag_prefix: "v"
        major_pattern: "(MAJOR)"
        minor_pattern: "(MINOR)"
        format: "${major}.${minor}.${patch}"
        short_tags: false
        bump_each_commit: true
      outputs:
        version: ${{ steps.version.outputs.version }}
        artifact_name: ${{ steps.version.outputs.major }}${{ steps.version.outputs.minor }}${{ steps.version.outputs.patch }}

  BuildDeploymentPackage:
    name: Build Deployment Package
    uses: mikelazell/rails-fulfilment/.github/workflows/package.yml@master
    with:
      ARTIFACT_NAME: ${{ jobs.GenerateVersion.outputs.artifact_name }}

  DeployTest:
    name: Deploy to Test 
    needs: [Test]
    uses: mikelazell/rails-fulfilment/.github/workflows/deploy.yml@master
    concurrency:
      group: fulfilment-deploy-test
    with:
      ENVIRONMENT_NAME: "test"
      REGION: "eu-west-2"
      VERSION: ${{ jobs.GenerateVersion.outputs.version }}$
      ARTIFACT_NAME: ${{ jobs.GenerateVersion.outputs.artifact_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      RAILS_APP_NAME: "eb-fulfilment-test-euwest2"
      RAILS_APP_SECRET_KEY_BASE: ${{secrets.RAILS_APP_SECRET_KEY_BASE}}

  DeployProd:
    name: Deploy to Prod 
    needs: [DeployTest]
    uses: mikelazell/rails-fulfilment/.github/workflows/deploy.yml@master
    concurrency:
      group: fulfilment-deploy-prod
    with:
      ENVIRONMENT_NAME: "production"
      REGION: "eu-west-2"
      VERSION: ${{ jobs.GenerateVersion.outputs.version }}$
      ARTIFACT_NAME: ${{ jobs.GenerateVersion.outputs.artifact_name }}
    secrets:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      DATABASE_NAME: ${{secrets.DATABASE_NAME}}
      DATABASE_USER: ${{secrets.DATABASE_USER}}
      DATABASE_PASSWORD: ${{secrets.DATABASE_PASSWORD}}
      RAILS_APP_NAME: "eb-fulfilment-production-euwest2"
      RAILS_APP_SECRET_KEY_BASE: ${{secrets.RAILS_APP_SECRET_KEY_BASE}}
