name: Package

on:
  workflow_call:
    inputs:
      ARTIFACT_NAME:
        required: true
        type: string

jobs:
  Package:
    name: 'Package'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash

    steps:
    - uses: actions/checkout@v2
    - name: Generate artifact
      uses: actions/upload-artifact@v2
      with: 
        name: ${{ inputs.ARTIFACT_NAME }}
        path: src
