name: Test
on:
  #This will run on PR creation and then when called explicitly (as a reusable workflow)
  pull_request:
    branches: [ master ]
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: 'src'
    services:
      db: 
        image: postgres:11@sha256:85d79cba2d4942dad7c99f84ec389a5b9cc84fb07a3dcd3aff0fb06948cdc03b
        env:
          POSTGRES\_USER: postgres
          POSTGRES\_PASSWORD: postgres
          POSTGRES\_DB: postgres
        ports: ['5432:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
          
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 3.0.x
      - uses: borales/actions-yarn@v2.0.0
        with: 
          cmd: install
      - name: Build and run tests
        env:
          DATABASE_URL: postgres://postgres:@localhost:5432/test
          RAILS_ENV: test
          RAILS_MASTER_KEY: ${{ secrets.RAILS_MASTER_KEY }}
        run: |
          sudo apt-get -yqq install libpq-dev
          gem install bundler
          bundle install  --jobs 4 --retry 3
          bundle exec rails db:prepare
          bundle exec rails test
          
